
/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val: string | undefined, defaultPort: number): number {
  if (val === undefined) {
    return defaultPort
  }
  const port = parseInt(val, 10)

  if (isNaN(port)) {
    // named pipe
    return defaultPort
  }

  if (port >= 0) {
    // port number
    return port
  }

  return defaultPort
}

export default {
  keys: {
    CAPTAIN_DOCKER_API: 'CAPTAIN_DOCKER_API',
    CAPTAIN_IS_DEBUG: 'CAPTAIN_IS_DEBUG',
    DEFAULT_PASSWORD: 'DEFAULT_PASSWORD',
    IS_CAPTAIN_INSTANCE: 'IS_CAPTAIN_INSTANCE',
    DEMO_MODE_ADMIN_IP: 'DEMO_MODE_ADMIN_IP',
    CAPTAIN_BASE_DIRECTORY: 'CAPTAIN_BASE_DIRECTORY',
    CAPTAIN_CONTAINER_HTTP_PORT: 'CAPTAIN_CONTAINER_HTTP_PORT',
    CAPTAIN_HOST_HTTP_PORT: 'CAPTAIN_HOST_HTTP_PORT',
    CAPTAIN_CONTAINER_HTTPS_PORT: 'CAPTAIN_CONTAINER_HTTPS_PORT',
    CAPTAIN_HOST_HTTPS_PORT: 'CAPTAIN_HOST_HTTPS_PORT',
    CAPTAIN_CONTAINER_ADMIN_PORT: 'CAPTAIN_CONTAINER_ADMIN_PORT',
    CAPTAIN_HOST_ADMIN_PORT: 'CAPTAIN_HOST_ADMIN_PORT',
    MAIN_NODE_IP_ADDRESS: 'MAIN_NODE_IP_ADDRESS',
    BY_PASS_PROXY_CHECK: 'BY_PASS_PROXY_CHECK',
    ACCEPTED_TERMS: 'ACCEPTED_TERMS',
    FORCE_ENABLE_PRO: 'FORCE_ENABLE_PRO',
    CAPROVER_DISABLE_ANALYTICS: 'CAPROVER_DISABLE_ANALYTICS',
    USE_EXISTING_SWARM: 'USE_EXISTING_SWARM',
    SHOW_DOCKER_COMMANDS: 'SHOW_DOCKER_COMMANDS',
  },

  BY_PASS_PROXY_CHECK: process.env.BY_PASS_PROXY_CHECK,

  CAPTAIN_DOCKER_API: process.env.CAPTAIN_DOCKER_API,

  CAPTAIN_IS_DEBUG: !!process.env.CAPTAIN_IS_DEBUG,

  SHOW_DOCKER_COMMANDS: !!process.env.SHOW_DOCKER_COMMANDS,

  CAPTAIN_CONTAINER_HTTP_PORT: normalizePort(process.env.CAPTAIN_CONTAINER_HTTP_PORT, 80),

  CAPTAIN_HOST_HTTP_PORT: normalizePort(process.env.CAPTAIN_HOST_HTTP_PORT, 10080),

  CAPTAIN_CONTAINER_HTTPS_PORT: normalizePort(process.env.CAPTAIN_CONTAINER_HTTPS_PORT, 443),

  CAPTAIN_HOST_HTTPS_PORT: normalizePort(process.env.CAPTAIN_HOST_HTTPS_PORT, 10443),

  CAPTAIN_CONTAINER_ADMIN_PORT: normalizePort(process.env.CAPTAIN_CONTAINER_ADMIN_PORT, 3000),

  CAPTAIN_HOST_ADMIN_PORT: normalizePort(process.env.CAPTAIN_HOST_ADMIN_PORT, 13000),

  MAIN_NODE_IP_ADDRESS: process.env.MAIN_NODE_IP_ADDRESS,

  USE_EXISTING_SWARM: !!process.env.USE_EXISTING_SWARM,

  ACCEPTED_TERMS: !!process.env.ACCEPTED_TERMS,

  IS_CAPTAIN_INSTANCE: process.env.IS_CAPTAIN_INSTANCE,

  DEMO_MODE_ADMIN_IP: process.env.DEMO_MODE_ADMIN_IP,

  DEFAULT_PASSWORD: process.env.DEFAULT_PASSWORD,

  FORCE_ENABLE_PRO: process.env.FORCE_ENABLE_PRO,

  CAPROVER_DISABLE_ANALYTICS:
    !!process.env.CAPROVER_DISABLE_ANALYTICS || !!process.env.DO_NOT_TRACK,

  CAPTAIN_BASE_DIRECTORY: process.env.CAPTAIN_BASE_DIRECTORY,
}
